# Generated by Django 4.1 on 2022-08-27 04:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman_Vote_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(default='...', max_length=200)),
                ('voter_name', models.CharField(max_length=200)),
                ('candidate_name', models.CharField(max_length=200)),
                ('icon_name', models.CharField(default='....', max_length=100)),
                ('ballot_paper_img', models.ImageField(upload_to='myimage')),
            ],
        ),
        migrations.CreateModel(
            name='Member_Vote_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(default='...', max_length=200)),
                ('voter_name', models.CharField(max_length=200)),
                ('candidate_name', models.CharField(max_length=200)),
                ('icon_name', models.CharField(default='....', max_length=100)),
                ('ballot_paper_img', models.ImageField(upload_to='myimage')),
            ],
        ),
        migrations.CreateModel(
            name='Nomination_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('icon_name', models.CharField(default='....', max_length=100)),
                ('ballot_paper_img', models.ImageField(upload_to='myimage')),
                ('position', models.CharField(choices=[('Chairman', 'Chairman'), ('Member', 'Member')], default='...', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nomination_paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Chairman', 'Chairman'), ('Member', 'Member')], default='Member', max_length=50)),
                ('paper_img', models.ImageField(upload_to='myimage')),
            ],
        ),
        migrations.CreateModel(
            name='Vote_Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter_Registration',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=200)),
                ('dob', models.DateTimeField()),
                ('village', models.CharField(max_length=150)),
                ('post_office', models.CharField(max_length=150)),
                ('upazilla', models.CharField(max_length=150)),
                ('zilla', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(upload_to='myimage')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
